using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Agency.Huddle.Seeder.Model;

namespace Agency.Huddle.Seeder.Writing;

/// <summary>Renders <c>manifest.md</c>: every entity that was created and the facts a tester can assert, generated from the same plan that was written.</summary>
internal static partial class ManifestWriter
{
    private static readonly string[] Finished = ["Done", "Cancelled", "Duplicate", "Rejected"];

    /// <summary>Renders the manifest.</summary>
    /// <param name="plan">What was written.</param>
    /// <param name="ids">The ids the database assigned.</param>
    /// <param name="root">The seed root.</param>
    /// <returns>The Markdown text.</returns>
    internal static string Render(SeedPlan plan, DatabaseResult ids, string root)
    {
        StringBuilder text = new();
        text.Append("# Seed manifest: ").Append(plan.Scenario).Append("\n\n");
        text.Append("Generated by `huddle-seed`; do not edit. Every date is an offset from the run date, so counts and states\n");
        text.Append("are stable but the date strings change with each run.\n\n");
        text.Append("| | |\n| --- | --- |\n");
        text.Append("| Run date | ").Append(plan.Today.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)).Append(" |\n");
        text.Append("| Seed root | `").Append(root).Append("` |\n");
        text.Append("| Data folder | `").Append(Path.Combine(root, "data")).Append("` |\n");
        text.Append("| Human | ").Append(plan.HumanName).Append(" |\n\n");

        AppendTeammates(text, plan, ids);
        AppendTeams(text, plan);
        AppendTasks(text, plan);
        AppendRooms(text, plan, ids);
        AppendViews(text, plan);
        AppendNotes(text, plan);
        AppendCoverage(text, plan);
        return text.ToString();
    }

    /// <summary>Whether a Task is finished, meaning it no longer blocks anything and is never overdue.</summary>
    /// <param name="status">The Task status.</param>
    /// <returns><see langword="true"/> for Done, Cancelled, Duplicate and Rejected.</returns>
    internal static bool IsFinished(string status) => Finished.Contains(status, StringComparer.Ordinal);

    /// <summary>The Task ids that are overdue on the run date.</summary>
    /// <param name="plan">The plan.</param>
    /// <returns>Ids whose due date is in the past and whose status is not finished.</returns>
    internal static IReadOnlyList<string> Overdue(SeedPlan plan) =>
        [.. plan.Tasks.Where(t => t.DueOffset < 0 && !IsFinished(t.Status)).Select(t => t.Id)];

    /// <summary>The Task ids blocked by at least one Task that exists and is not finished.</summary>
    /// <param name="plan">The plan.</param>
    /// <returns>The blocked ids.</returns>
    internal static IReadOnlyList<string> Blocked(SeedPlan plan) =>
        [.. plan.Tasks.Where(t => IsBlocked(plan, t)).Select(t => t.Id)];

    /// <summary>Which notes link to which, by file name without extension.</summary>
    /// <param name="plan">The plan.</param>
    /// <returns>For each Library note, the link targets it contains.</returns>
    internal static IReadOnlyDictionary<string, IReadOnlyList<string>> LinksByNote(SeedPlan plan)
    {
        Dictionary<string, IReadOnlyList<string>> links = new(StringComparer.OrdinalIgnoreCase);
        foreach (SeedFile file in NoteFiles(plan))
        {
            links[NoteName(file)] = [.. WikiLink().Matches(file.Content).Select(m => m.Groups[1].Value.Trim()).Distinct(StringComparer.OrdinalIgnoreCase)];
        }

        return links;
    }

    private static bool IsBlocked(SeedPlan plan, SeedTask task) =>
        task.BlockedBy.Any(id => plan.Tasks.FirstOrDefault(t => t.Id == id) is { } blocker && !IsFinished(blocker.Status));

    private static IEnumerable<SeedFile> NoteFiles(SeedPlan plan) =>
        plan.Files.Where(f => f.RelativePath.EndsWith(".md", StringComparison.Ordinal) && !f.RelativePath.Contains("/memory/", StringComparison.Ordinal));

    private static string NoteName(SeedFile file) => Path.GetFileNameWithoutExtension(file.RelativePath);

    private static void AppendTeammates(StringBuilder text, SeedPlan plan, DatabaseResult ids)
    {
        text.Append("## Teammates\n\n| Name | Alias | Title | Teams | Skills | User id |\n| --- | --- | --- | --- | --- | --- |\n");
        foreach (SeedTeammate t in plan.Teammates)
        {
            text.Append(CultureInfo.InvariantCulture, $"| {t.Name} | {t.Alias} | {t.Title} | {Join(t.Teams, "none")} | {Join(t.Skills, "none")} | `{ids.UserIds[t.Name]}` |\n");
        }

        text.Append("\nThe built-in Chief of Staff is created by Huddle on first start and belongs to no Team.\n\n");
    }

    private static void AppendTeams(StringBuilder text, SeedPlan plan)
    {
        text.Append("## Teams\n\n| Team | Members | Projects | Tasks | Memory facts |\n| --- | --- | --- | --- | --- |\n");
        foreach (SeedTeam team in plan.Teams)
        {
            string[] members = [.. plan.Teammates.Where(t => t.Teams.Contains(team.Name, StringComparer.OrdinalIgnoreCase)).Select(t => t.Name)];
            int tasks = plan.Tasks.Count(t => t.Location.Team == team.Name);
            int memory = plan.Files.Count(f => f.RelativePath.StartsWith($"Teams/{team.Name}/", StringComparison.Ordinal) && f.RelativePath.Contains("/memory/", StringComparison.Ordinal));
            text.Append(CultureInfo.InvariantCulture, $"| {team.Name} | {Join(members, "none")} | {Join(team.Projects, "none")} | {tasks} | {memory} |\n");
        }

        text.Append('\n');
    }

    private static void AppendTasks(StringBuilder text, SeedPlan plan)
    {
        text.Append("## Tasks\n\n| Id | Where | Title | Status | Priority | Assignee | Closed | Due | Blocked by | Parent |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n");
        foreach (SeedTask t in plan.Tasks)
        {
            string due = t.DueOffset is { } d ? TaskFileWriter.Date(plan.Today, d) : "-";
            text.Append(CultureInfo.InvariantCulture, $"| {t.Id} | {t.Location.Path} | {t.Title} | {t.Status} | {t.Priority} | {t.Assignee ?? "unassigned"} | {(t.Closed ? "yes" : "no")} | {due} | {Join(t.BlockedBy, "-")} | {t.Parent ?? "-"} |\n");
        }

        text.Append("\nOpen Tasks: ").Append(plan.Tasks.Count(t => !t.Closed)).Append(", closed: ").Append(plan.Tasks.Count(t => t.Closed)).Append(".\n\n");
    }

    private static void AppendRooms(StringBuilder text, SeedPlan plan, DatabaseResult ids)
    {
        text.Append("## Rooms\n\n| Name | Room id | Members | Messages | Archived |\n| --- | --- | --- | --- | --- |\n");
        foreach (SeedRoom r in plan.Rooms)
        {
            text.Append(CultureInfo.InvariantCulture, $"| {r.Name} | `{ids.RoomIds[r.Key]}` | {plan.HumanName}, {Join(r.Members, "none")} | {r.Messages.Count} | {(r.Archived ? "yes" : "no")} |\n");
        }

        text.Append('\n');
    }

    private static void AppendViews(StringBuilder text, SeedPlan plan)
    {
        text.Append("## Views\n\n| Id | Name | Kind | Scope | Expected Task ids |\n| --- | --- | --- | --- | --- |\n");
        using JsonDocument document = JsonDocument.Parse(plan.ViewsJson);
        foreach (JsonElement view in document.RootElement.GetProperty("views").EnumerateArray())
        {
            string scope = view.GetProperty("scope").GetString() ?? "active";
            string[] expected = [.. plan.Tasks.Where(t => Matches(plan, view, t, scope)).Select(t => t.Id)];
            text.Append(CultureInfo.InvariantCulture, $"| {view.GetProperty("id").GetString()} | {view.GetProperty("name").GetString()} | {view.GetProperty("kind").GetString()} | {scope} | {Join(expected, "none")} |\n");
        }

        text.Append('\n');
    }

    private static bool Matches(SeedPlan plan, JsonElement view, SeedTask task, string scope)
    {
        if (task.Closed != string.Equals(scope, "closed", StringComparison.Ordinal))
        {
            return false;
        }

        JsonElement filter = view.GetProperty("filter");
        return Allows(filter, "teams", task.Location.Team)
            && Allows(filter, "states", task.Status)
            && Allows(filter, "priorities", task.Priority)
            && AllowsAssignee(plan, filter, task)
            && AllowsBlocked(plan, filter, task);
    }

    private static bool Allows(JsonElement filter, string property, string value) =>
        !filter.TryGetProperty(property, out JsonElement list)
        || list.EnumerateArray().Any(e => string.Equals(e.GetString(), value, StringComparison.OrdinalIgnoreCase));

    private static bool AllowsAssignee(SeedPlan plan, JsonElement filter, SeedTask task)
    {
        if (!filter.TryGetProperty("assignees", out JsonElement list))
        {
            return true;
        }

        return list.EnumerateArray().Select(e => e.GetString()).Any(a => a switch
        {
            "@me" => string.Equals(task.Assignee, plan.HumanName, StringComparison.Ordinal),
            "@unassigned" => task.Assignee is null,
            _ => string.Equals(task.Assignee, a, StringComparison.OrdinalIgnoreCase),
        });
    }

    private static bool AllowsBlocked(SeedPlan plan, JsonElement filter, SeedTask task) =>
        !filter.TryGetProperty("blocked", out JsonElement mode) || mode.GetString() switch
        {
            "blocked" => IsBlocked(plan, task),
            "unblocked" => !IsBlocked(plan, task),
            _ => true,
        };

    private static void AppendNotes(StringBuilder text, SeedPlan plan)
    {
        IReadOnlyDictionary<string, IReadOnlyList<string>> links = LinksByNote(plan);
        text.Append("## Library notes\n\n| Note | Links to | Backlinks from |\n| --- | --- | --- |\n");
        foreach (SeedFile file in NoteFiles(plan))
        {
            string name = NoteName(file);
            string[] backlinks = [.. links.Where(l => l.Value.Contains(name, StringComparer.OrdinalIgnoreCase)).Select(l => l.Key)];
            string[] targets = [.. links[name].Select(l => links.ContainsKey(l) ? l : l + " (unresolved)")];
            text.Append(CultureInfo.InvariantCulture, $"| `{file.RelativePath}` | {Join(targets, "-")} | {Join(backlinks, "-")} |\n");
        }

        text.Append('\n');
    }

    private static void AppendCoverage(StringBuilder text, SeedPlan plan)
    {
        text.Append("## Facts a test can assert\n\n");
        text.Append("- Overdue: ").Append(Join(Overdue(plan), "none")).Append('\n');
        text.Append("- Blocked by an open Task: ").Append(Join(Blocked(plan), "none")).Append('\n');
        text.Append("- Blocked only by a finished Task (not blocked): ")
            .Append(Join(plan.Tasks.Where(t => t.BlockedBy.Count > 0 && !IsBlocked(plan, t)).Select(t => t.Id).ToList(), "none")).Append('\n');
        text.Append("- Sub-tasks: ").Append(Join(plan.Tasks.Where(t => t.Parent is not null).Select(t => $"{t.Id} of {t.Parent}").ToList(), "none")).Append('\n');
        text.Append("- Duplicates: ").Append(Join(plan.Tasks.Where(t => t.DuplicateOf is not null).Select(t => $"{t.Id} of {t.DuplicateOf}").ToList(), "none")).Append('\n');
        text.Append("- Unassigned: ").Append(Join(plan.Tasks.Where(t => t.Assignee is null).Select(t => t.Id).ToList(), "none")).Append('\n');
        text.Append("- Assigned to the Human: ").Append(Join(plan.Tasks.Where(t => t.Assignee == plan.HumanName).Select(t => t.Id).ToList(), "none")).Append('\n');
        text.Append("- Teammates in two or more Teams: ").Append(Join(plan.Teammates.Where(t => t.Teams.Count >= 2).Select(t => t.Name).ToList(), "none")).Append('\n');
        text.Append("- Teammates in no Team: ").Append(Join(plan.Teammates.Where(t => t.Teams.Count == 0).Select(t => t.Name).ToList(), "none")).Append('\n');
        text.Append("- Teams with no members: ").Append(Join(plan.Teams.Where(t => !plan.Teammates.Any(m => m.Teams.Contains(t.Name, StringComparer.OrdinalIgnoreCase))).Select(t => t.Name).ToList(), "none")).Append('\n');
        text.Append("- Teams with no Projects: ").Append(Join(plan.Teams.Where(t => t.Projects.Count == 0).Select(t => t.Name).ToList(), "none")).Append('\n');
        text.Append("- Projects with no Tasks: ").Append(Join(plan.Teams.SelectMany(t => t.Projects.Select(p => (Team: t.Name, Project: p))).Where(x => !plan.Tasks.Any(t => t.Location.Team == x.Team && t.Location.Project == x.Project)).Select(x => $"{x.Team}/{x.Project}").ToList(), "none")).Append('\n');
    }

    private static string Join(IEnumerable<string> values, string whenEmpty)
    {
        string joined = string.Join(", ", values);
        return joined.Length == 0 ? whenEmpty : joined;
    }

    [GeneratedRegex(@"\[\[([^\]|#]+)", RegexOptions.CultureInvariant)]
    private static partial Regex WikiLink();
}
