<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Agency.Huddle.Seeder</RootNamespace>
    <AssemblyName>huddle-seed</AssemblyName>
    <NoWarn>$(NoWarn);CA1303</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Huddle.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Huddle.App\Huddle.App.csproj" />
    <ProjectReference Include="..\Huddle.Contracts\Huddle.Contracts.csproj" />
  </ItemGroup>

</Project>
